### ISSUE TITLE
The full version of Beyond Waymark

### ISSUE THREAD

**Issue by gbudny** [octaspire/crates#6]
@octaspire

Hi

I know you created Beyond Waymark for Linux and Mac. I'm interested in buying these two versions of your game, but BMT Micro doesn't sell it.

I won't ask you any questions if I  have problems with this game.

Can you help me to buy it?

Do you need my email address to discuss it?

**Comment by octaspire** [comment]
Thank you for the interest, but the game has not been available for a long time, and after shutting down the company I don’t sell anything anymore.

So I only add free (as in beer and as in freedom) and open source projects here.

**Comment by gbudny** [comment]
> Thank you for the interest, but the game has not been available for a long time, and after shutting down the company I don’t sell anything anymore.
> 
> So I only add free (as in beer and as in freedom) and open source projects here.

Hi

Thank you for the answer

I didn't see your email address on Github, so I decided to post it here.

I appreciate that you are developing open source projects on GitHub.

I know it was an inexpensive game, so I can donate some more money to your open source projects. It would be great to receive Beyond Waymark for Linux, and Mac after I do it. 

I know it was a long time ago, and I have old computers with PCLinuxOS 2010, and Mac OS X 10.6. I won't ask you any questions about Beyond Waymark if I have problems with it.

Do you have any websites for donations?

You can contact me at if you want to discuss it.

**Comment by octaspire** [comment]
The game has been pretty much superseded by free and open source Octaspire Maze, that is written with my own programming language Octaspire Dern.  And Dern works in a very large number of devices; Unix likes (including macOS), GNU/Linux, Windows, even Amiga. And on older hardware. Maybe you might want take a look at Octaspire Dern and Octaspire Maze:

https://youtu.be/dRrRits8PaE?si=bJliQi9J2l_0FSx-

They both are available here, on my GitHub. I don’t have the old closed source game now available, and no plans to open source it. The Octaspire Maze should have more interesting features, too.

**Comment by octaspire** [comment]
PS. If you want to try Octaspire Maze, please use the new version that comes with Dern:
https://github.com/octaspire/dern
There is a separate, old and archived repository for the game, but that is old and only kept as an archive. Please use the new version of the game that comes with the Dern language.

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

It's great that there are some open source alternatives to Beyond Waymark. Unfortunately, those aren't the same game. Additionally, it won't be too enjoyable to play them with the awareness that your best game isn't available for me. I remember when you released Beyond Waymark in 2011. I regret I didn't buy it back then.

I would never ask you about releasing the source code for a commercial game. I understand it's always an author's decision, and the source code for many commercial games can't be released.

I can't donate $30 to your open source projects if I get a chance to play the full version of Beyond Waymark on Linux and Mac. I suspect it could be tricky to find this game, but I can wait weeks or even months for it. The demo works well on PCLinuxOS 2010 and Mac OS X 10.6:

![Screenshot](https://github.com/user-attachments/assets/1c7966eb-2af6-4ab8-8378-321d41ba9fb1)

![Screen shot 2024-11-08 at 9 39 19 PM](https://github.com/user-attachments/assets/3098e583-cf41-4829-bb56-2df6625c12e5)

I won't ask any questions if I have problems with them. I hope you can make this exception and allow me to play it.

**Comment by octaspire** [comment]
Thank you for the kind words, and interest in the game. However, I don’t have copies of the game anywhere at hand. It was  sunset many years ago, and I concentrated to other things after that. Also, I don’t have much time now to use for these projects.

And what comes to my best game, I don’t think Beyond Waymark, or the lite version for mobile phones was that. Of course, I worked with them very hard, because I was selling them. But the original Octaspire Crates, or Octaspire Dern with Octaspire Maze and other things are my favorites and my best work thus far. Crates, because it was the first, and Dern, because it is my own obscure programming language (Dern means ”obscure language”) build from scratch all by myself. And then I wrote Maze and the other games with it. The newer game has also some new improvements and ideas. And it is free software. Dern is interesting also because it runs on very large number of systems. Systems like ”Amiga, Haiku, Plan9, Unix, Windows and almost anything between.”,  as the documentation states. There was huge amount of work to test it on all those wonderfull systems after updates. I would especially want to point out Haiku and Plan9 that are interesting systems.

I will close this issue now. I hope that you might find the original Crates or Dern with Maze and other things nice. Sadly, I cannot provide a copy of the old game, and I think the newer things are more interesting anyway.

All the best.
